### PR TITLE
Merge WMT20 code into master branch

### PR DESCRIPTION
**Pull request by cfedermann**
Changes proposed in the pull request:

- Merge WMT20 code

@AppraiseDev/core-team

### CODE REVIEW

**Review by cfedermann — COMMENTED** [review]
@snukky: this is good to be merged, can you please check the PR and approve? Thanks!

**Comment by snukky** [comment]
A few first comments after setting up a fresh environment with this branch:
1. Some tests fail after `python manage.py test`. We should fix them or temporarily disable.
2. `python manage.py collectstatic` overwrites some static files. I think ideally we should add `static` to `.gitignore` and should not keep static files in the repository.
3. A minor issue: python formatting checks fail for 3 files.

**Comment by cfedermann** [comment]
Thanks, @snukky -- 1. and 3. are blockers, 2. seems unrelated to the changes in wmt20 branch.

**Comment by cfedermann** [comment]
I'll fix and send an updated PR.

**Comment by snukky** [comment]
Point 2 is semi-related because this branch changes `requirements.txt`, which in turn, generates slightly newer version of static files than the ones already in the repository. I agree it might be better to do this in a separate PR.

**Comment by cfedermann** [comment]
Fixed 1. by removing outdated tests, 3. by running `black -S -l 75` on affected files. Also updated `requirements.txt` to latest, compatible versions to avoid `lxml` issues with versions <4.6.2.

**Pull request merged**
